<?php

/**
 * Fixed pick-lists for the Add / Edit Proposal form (client's lists). Both end with
 * "Other — add manually" in the form, which lets the team type a value that is not listed.
 */
return [
    'education' => [
        'No Formal Education',
        'Primary / Middle',
        'Matric / GCSE / O-Level',
        'Intermediate / FA / FSc / I.Com / ICS / A-Level',
        'Diploma / DAE',
        'Associate Degree / ADP',
        "Bachelor's / BS",
        "Master's / MA / MSc",
        'MPhil / MS',
        'PhD / Doctorate',
        'MBBS / MD',
        'BDS / Dentistry',
        'FCPS / MRCP / Medical Specialization',
        'Pharm-D / Pharmacy',
        'DPT / Physiotherapy',
        'Nursing',
        'Engineering',
        'Computer Science / IT',
        'BBA / MBA / Business',
        'CA',
        'ACCA',
        'CFA / Finance',
        'CPA / Accounting',
        'LLB / LLM / Law',
        'CSS / Civil Services Qualification',
        'Architecture',
        'Education / Teaching',
        'Islamic / Religious Education',
        'Professional Certification / Qualification',
        'Foreign Qualification',
    ],

    'profession' => [
        'Doctor / Physician',
        'Specialist Doctor / Surgeon',
        'Dentist',
        'Pharmacist',
        'Physiotherapist',
        'Nurse / Healthcare Professional',
        'Psychologist / Therapist',
        'Engineer',
        'Software Engineer / Developer',
        'IT / Technology Professional',
        'Data Scientist / AI Professional',
        'Cybersecurity Professional',
        'Architect',
        'Chartered Accountant (CA)',
        'ACCA / Accountant',
        'Finance / Banking Professional',
        'Investment / Wealth Management',
        'Business Owner / Entrepreneur',
        'CEO / Director / Executive',
        'Manager / Senior Management',
        'Sales / Marketing Professional',
        'HR Professional',
        'Lawyer / Advocate',
        'Judge / Legal Professional',
        'Civil Servant / Government Officer',
        'CSS / PAS / PSP Officer',
        'Armed Forces Officer',
        'Police / Law Enforcement',
        'Pilot / Aviation Professional',
        'Professor / Lecturer',
        'Teacher / Education Professional',
        'Researcher / Scientist',
        'Consultant',
        'Project / Program Manager',
        'Real Estate / Property Business',
        'Construction Professional / Contractor',
        'Import / Export Business',
        'Textile / Manufacturing Business',
        'Retail / E-commerce Business',
        'Media / Journalist / Anchor',
        'Actor / Model / Artist',
        'Content Creator / Influencer',
        'Designer / Fashion Professional',
        'Hospitality / Hotel Professional',
        'Chef / Food Business',
        'Government Employee',
        'Private Sector Employee',
        'NGO / Development Sector',
        'Freelancer / Self-Employed',
        'Student',
        'Homemaker / Housewife',
        'Retired',
        'Not Currently Working',
        'Family Business',
        'Religious Scholar',
        'Agriculture / Farming / Landowner',
        'Overseas Professional',
    ],
    /*
     * Countries (name => ISO code, used for the flag) and the matching nationalities — the same 42 places in the
     * same order, so nationalities[i] is the nationality of countries[i]. Both dropdowns end with
     * "Other — Add Manually".
     */
    'countries' => [
        'Pakistan' => 'PK', 'United Kingdom (UK)' => 'GB', 'United States (USA)' => 'US', 'Canada' => 'CA', 'Australia' => 'AU',
        'United Arab Emirates (UAE)' => 'AE', 'Saudi Arabia' => 'SA', 'Qatar' => 'QA', 'Kuwait' => 'KW', 'Oman' => 'OM',
        'Bahrain' => 'BH', 'Germany' => 'DE', 'France' => 'FR', 'Italy' => 'IT', 'Spain' => 'ES', 'Netherlands' => 'NL',
        'Belgium' => 'BE', 'Switzerland' => 'CH', 'Sweden' => 'SE', 'Norway' => 'NO', 'Denmark' => 'DK', 'Ireland' => 'IE',
        'Austria' => 'AT', 'New Zealand' => 'NZ', 'Turkey' => 'TR', 'Azerbaijan' => 'AZ', 'Malaysia' => 'MY', 'Singapore' => 'SG',
        'South Africa' => 'ZA', 'India' => 'IN', 'Bangladesh' => 'BD', 'Sri Lanka' => 'LK', 'Afghanistan' => 'AF', 'Iran' => 'IR',
        'Iraq' => 'IQ', 'Jordan' => 'JO', 'Egypt' => 'EG', 'Lebanon' => 'LB', 'Morocco' => 'MA', 'China' => 'CN', 'Japan' => 'JP',
        'South Korea' => 'KR',
    ],

    'nationalities' => [
        'Pakistani', 'British', 'American', 'Canadian', 'Australian', 'Emirati', 'Saudi Arabian', 'Qatari', 'Kuwaiti', 'Omani',
        'Bahraini', 'German', 'French', 'Italian', 'Spanish', 'Dutch', 'Belgian', 'Swiss', 'Swedish', 'Norwegian', 'Danish',
        'Irish', 'Austrian', 'New Zealander', 'Turkish', 'Azerbaijani', 'Malaysian', 'Singaporean', 'South African', 'Indian',
        'Bangladeshi', 'Sri Lankan', 'Afghan', 'Iranian', 'Iraqi', 'Jordanian', 'Egyptian', 'Lebanese', 'Moroccan', 'Chinese',
        'Japanese', 'South Korean',
    ],
];
